test_service:
  container_name: my_service
  build: .
  ports:
    - "80:8080"
  volumes:
    - ./code:/srv/www
  links:
    - redis
  command:  http-server 

redis:
  container_name: my_redis
  image: redis
  ports:
    - "6379:6379"